CREATE TABLE USERS
(
    ID       BIGINT                  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL    VARCHAR_IGNORECASE(100) NOT NULL,
    NAME     VARCHAR_IGNORECASE(100) NOT NULL,
    PASSWORD VARCHAR_IGNORECASE(255) NOT NULL,
    ENABLED  BOOLEAN                 NOT NULL
);

CREATE TABLE ROLES
(
    ID   BIGINT                  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR_IGNORECASE(100) NOT NULL
);

CREATE TABLE AUTHORITIES
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL
);

CREATE TABLE ACCOUNTS
(
    USER_ID BIGINT                  NOT NULL,
    CUR     VARCHAR_IGNORECASE(100) NOT NULL,
    SUM     DOUBLE                  NOT NULL
);

CREATE TABLE CATEGORIES
(
    ID       BIGINT                  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME     VARCHAR_IGNORECASE(100) NOT NULL,
    CAPACITY DOUBLE                  NOT NULL
);

ALTER TABLE AUTHORITIES
    ADD CONSTRAINT AUTHORITIES_UNIQUE UNIQUE (USER_ID, ROLE_ID);
ALTER TABLE AUTHORITIES
    ADD FOREIGN KEY (USER_ID) REFERENCES USERS (ID);
ALTER TABLE AUTHORITIES
    ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID);
ALTER TABLE ACCOUNTS
    ADD FOREIGN KEY (USER_ID) REFERENCES USERS (ID);
